print("#####################")
print(" Band-Name-Generator ")
print("#####################")
print()
print("Answer the next questions to get a fancy band name!")
print()
city_name = input("What city did you grew up in?\n")
pet_name = input("What was your first pet's name?\n")
print("Wow cool! Your band name is: '" + city_name + " " + pet_name + "'!")
